language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn run test
  # - yarn build
after_script: # Upload coverage reports
  - yarn run coveralls
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls