language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test -- --coverage
  # - yarn build
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls